name: Upload ProxyTools to Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Download ProxyTools
        run: |
            url=$(wget -O- "https://api.github.com/repos/shadowsocks/shadowsocks-rust/releases/latest" | grep -Eo '\"https.*?x86_64-unknown-linux-musl.tar.xz\"'  | tr -d \") 
            wget $url && tar xf shadowsocks-*.tar.xz
            url=$(wget -O- "https://api.github.com/repos/v2fly/v2ray-core/releases/latest" | grep -Eo '\"https.*?v2ray-linux-64.zip\"'  | tr -d \")
            wget $url && unzip v2ray-linux-64.zip && mv v2ray vserver
            url=$(wget -O- "https://api.github.com/repos/maskedeken/gost-plugin/releases/latest" | grep -Eo 'https.*?gost-plugin-linux-amd64.*?gz') 
            wget "$url" && tar xf gost-plugin-linux-amd64*.tar.gz
            url=$(wget -O- "https://api.github.com/repos/e1732a364fed/v2ray_simple/releases/latest" | grep -Eo 'https.*?verysimple_linux_amd64.tar.xz') 
            wget "$url" && tar xf verysimple_linux_amd64.tar.xz
            wget 'https://dl.lamp.sh/files/v''2r''a''y-plugin_linux_amd64' -O v2-plugin

      - name: Upload ProxyTools
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release create latest ./linux-amd64/gost-plugin v2-plugin ssserver vserver verysimple
